name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: pinoched

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Docker Image Frontend
      run: |
        VERSION=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file ./src/app/Dockerfile -t $REGISTRY/frontend:$VERSION -t $REGISTRY/frontend:latest
        docker push $REGISTRY/frontend:$VERSION --all-tags

    - name: Build the Docker Image Consumer
      run: |
        VERSION=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file ./src/consumer/Dockerfile -t $REGISTRY/consumer:$VERSION -t $REGISTRY/consumer:latest
        docker push $REGISTRY/consumer:$VERSION
      
