name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: pinoched

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image Frontend
      run: |
        VERSION=$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file ./src/app/Dockerfile --tag frontend:$VERSION
        docker images
      
